### ISSUE TITLE
Error for date value

### ISSUE THREAD

**Issue by azjamsg** [azjamsg/Crisp-Project#2]
The date has this error 
"script1.js:313 The specified value "2021-05-19T16:00:00.000Z" does not conform to the required format, "yyyy-MM-dd"."

//After edit operation, need to show updated data in an HTML table
function updateRecord(formData) {
    selectedRow.cells[2].innerHTML = formData.date; <== this line has error
    selectedRow.cells[5].innerHTML = formData.amount;
    selectedRow.cells[4].innerHTML = formData.desc;
}

**Comment by Chewzhiyan** [comment]
Frontend uses date type: dd/mm/yyyy
Propose to change backend to just date, so that user do not have to input both date and time from the front end

**Comment by eunicech9** [comment]
Changed on backend>CrispAPI.js  for "Get transactions by category and user_id" API to show date as dd/mm/yyyy

`SELECT t.*, date_format(t.transaction_date,'%d/%m/20%y')as transaction_date, c.category 
  FROM transactions as t

**Comment by eunicech9** [comment]
Changed on backend>CrispAPI.js for "Get transactions by category and user_id" API to show date as YYYY-MM-DD

`SELECT t.*, date_format(t.transaction_date,'20%y/%m/20%d')as transaction_date, c.category
FROM transactions as t
